name : build & deploy

on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : Deploy Express App
        uses : appleboy/ssh-action@v0.1.2
        with :
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            cd /var/www/imx-buy-bot/
            git pull git@github.com:Terminev/imx-buy-bot.git
            npm install
            echo "Deploy OK"
            pm2 delete all
            pm2 start "yarn -s buy-eth >> /home/terminev/logs/buy-eth.log"
            pm2 start "yarn -s buy-imx >> /home/terminev/logs/buy-imx.log"
            pm2 start "yarn -s buy-usdc >> /home/terminev/logs/buy-usdc.log"

